Merging Feature Branch
Kyle-Law/library pull request #1
Opened 2020-08-12 09:50 UTC by Kyle-Law

- Live Version here: https://rawcdn.githack.com/Kyle-Law/library/528b0d400200b27516fec213b41da831344715cf/index.html

- User can add new book
- User can toggle read/unread
- User can remove book
- The state is persistent through local storage variable named 'myLibrary'

2020-08-12 15:05 UTC, Torres-ssf requested changes
### Changes required :muscle: 
Hi There @Kyle-Law :hand: 
Awesome job on this project so far :clap: 
But we need to make some changes before moving on :+1: 

- [ ] The `.stylelintrc.json` file is different from the one provided by Microverse. We should use this [one](https://github.com/microverseinc/linters-config/blob/master/javascript/.stylelintrc.json)

- [ ] Right now is possible to create books without providing any book information. We need to block that kind of behavior and only allow to create a book when all required information is provided. We also need to be carefully to not allow the number of pages to be 0 or a negative number, like: `-50`

Please kindly submit for code review again after implementing these changes.
Feel free to message me on slack if you have any questions :smile: 
Happy Coding :computer: 
**Sergio Torres**

2020-08-12 15:05 UTC, Torres-ssf commented on script.js
> +}
- [ ] The requirements specifically ask to implement a property `pages` for the Book object but a `price` property was implemented instead. We need to also add the `pages` property as requested.
![Screenshot from 2020-08-12 11-59-41](https://user-images.githubusercontent.com/30977845/90031228-5dc95400-dc93-11ea-863b-77e82f5580e2.png)

2020-08-12 17:10 UTC, Kyle-Law commented
Thank you for reviewing my project! Your recommendations have been implemented as below:
- Form validations are added, especially for preventing negative prices and pages
- Stylelint changed but there's a bug of unable to find csstree/validator, I check with my colleagues and got it removed. Hence that's why "csstree/validator": true is removed from .stylelintrc.json. Feel free to suggest if there's any better resolution 👍 

Thanks and looking forward to another review :)

2020-08-13 13:09 UTC, rOluochKe requested changes
Hello @Kyle-Law 
### You have done well so far :clap: However, you have a few issues to fix:-
- [ ] Remove all the commented line in the codebase
- [ ] Once a user has created a book, make the modal to close after saving
- [ ] Separate app logic from the dom, this way it makes your app easy to read and maintain
- Happy Coding!

By Raymond
Slack @iamraymond

2020-08-13 13:10 UTC, rOluochKe commented on script.js
> +const bookStatusEl = document.getElementById('book-status');
### Separate this dom from logic

2020-08-13 13:10 UTC, rOluochKe commented on script.js
> +}
### Separate this logic from dom

2020-08-18 16:12 UTC, Kyle-Law commented
Good day! Thanks @rOluochKe for reviewing my project! Your recommendations have been implemented as followed:
- Unnecessary comments are removed
- Modal closes after a book is added
- scripts have modularized into 3 files -  Book.js, variables.js and script.js

Thanks and looking forward to another review :)

2020-08-18 21:05 UTC, bellom approved these changes
## Hi @Kyle-Law  :clap: 

**Great work making all the necessary corrections from the previous review.**

## Congratulation :+1:  
_Go ahead and merge to dev and don't forget to submit project completion form.
Good luck in the next project :slightly_smiling_face:_ 

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2020-09-03 08:26 UTC, merged